baseURL = 'https://issaNzamba.github.io/'
languageCode = 'fr-fr'
defaultContentLanguage = 'fr'  # <-- 1. Active la traduction automatique des mois par Hugo

title = 'Ingénieur Logiciel — Issa Nzamba'
theme = 'PaperMod'

[pagination]
  pagerSize = 5

[params]
  # 2. Choisir le format de date souhaité :

  # Option A : Format texte complet (ex: 24 juillet 2026)
  dateFormat = "2 January 2006"

  # Option B : Format numérique français (ex: 24/07/2026)
  # dateFormat = "02/01/2006"

  [params.profileMode]
    enabled = false

  [params.homeInfoParams]
    Title = "Ingénieur Logiciel"
    Content = "Architecture Software · Développement Web · APIs · Clean Code"

  
  # Icônes de contact direct et réseaux sociaux
  [[params.socialIcons]]
    name = "linkedin"
    url = "www.linkedin.com/in/issa-nzamba-399a47291"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/issaNzamba"

  [[params.socialIcons]]
    name = "youtube"
    url = "https://www.youtube.com/@issanzamba"

  

# Menu de navigation
[[menu.main]]
  name = "Articles"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "À propos & CV"
  url = "/about/"
  weight = 20

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 30